# DATA
FU0_R1_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R1.fq.gz"
FU0_R2_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R2.fq.gz"

MU0_R1_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R1.fq.gz"
MU0_R2_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R2.fq.gz"

CHILD_R1_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R1.fq.gz"
CHILD_R2_path: "/data/wangty/WES_pipeline_V2.2/example/2212B001/01.Cleandata/2212B001.R2.fq.gz"

TRIO_ID: "2212B001"
# OUT DIR
output_dir: "/data/wangty/tmp/trio_WES"

# PARAMETER
reference_panel_name: "hg38"

Psoft: "ReVe,gt,0.7:VEST3,gt,0.6:REVEL,gt,0.4:CADD,gt,20:GERP++,gt,2"
MPsoft: 0.6
MPsoft2: 0.1
MAFS: "gnomAD_exome_ALL,0.001:gnomad312_AF,0.001:gnomAD_exome_EAS,0.001:gnomad312_AF_eas,0.001:ExAC_EAS,0.001:ExAC_ALL,0.001:esp6500siv2_all,0.001:1000g2015aug_eas,0.001:1000g2015aug_all,0.001"

DNMs_p: 0.9
DNMs_c: 1

category: "genebased-hgmd-gene4denovo"

panel_type: "ASD"

# READ GROUP
FU0_sample_name: "FU0"
MU0_sample_name: "MU0"
CHILD_sample_name: "CHILD"
lane: "unit2"
platform: "Illumina"

# REF
bed_path: "/data/wangty/WES_pipeline_V2.2/lib/Human_Exome_Panel-hg38.bed"
reference_panel_path: "/data/wangty/my_ref/hg38.fa"
known_sites: "/data/wangty/my_ref/dbsnp_138.hg38.vcf.gz"
known_sites2: "/data/wangty/WES_pipeline_V2.2/database/hg38/dbsnp/Mills_and_1000G_gold_standard.indels.hg38.vcf" # ?????????

HPO: "/data/wangty/WES_pipeline_V2.2/database/HPO/HPO_database.txt"
GENEMODEL: "/data/wangty/WES_pipeline_V2.2/database/OMIM.20210712/gm.txt"
TRANSCRIPT: "/data/wangty/WES_pipeline_V2.2/lib/canonical_transcript.txt"
panel_path: "/data/wangty/WES_pipeline_V2.2/lib/gene_list/all.gene.txt"
acmg78_path: "/data/wangty/WES_pipeline_V2.2/lib/ACMG78.list"
database_path: "/data/wangty/WES_pipeline_V2.2/database/hg38/annovar"

# DenovoCNN model
snp_model: "/data/wangty/my_bin/DeNovoCNN-main/models/snp"
ins_model: "/data/wangty/my_bin/DeNovoCNN-main/models/ins"
del_model: "/data/wangty/my_bin/DeNovoCNN-main/models/del"

# BIN
gatk_path: "/data/wangty/my_bin/gatk-4.4.0.0/gatk"
FilterVar_path: "/data/wangty/WES_pipeline_V2.2/lib/FilterVar.pl"
DenovoCNN_env: "/data/wangty/my_bin/DeNovoCNN-main/environment.yml"
DenovoCNN_path: "/data/wangty/my_bin/DeNovoCNN-main/apply_denovocnn.sh"
FilterDNMs_path: "/data/wangty/WES_pipeline_V2.2/lib/FilterDNMs.pl"
ExtremeVar2_PATH: "/data/wangty/WES_pipeline_V2.2/lib/ExtremeVar2.pl"
ExtremeVar_PATH: "/data/wangty/WES_pipeline_V2.2/lib/ExtremeVar.pl"
process_trio_path: "/data/wangty/WES_pipeline_V2.2/lib/process_trio.pl"
process_Trios_path: "/data/wangty/WES_pipeline_V2.2/lib/process_Trios.pl" # Attention, different from process_trio.pl
ACMG_path: "/data/wangty/WES_pipeline_V2.2/lib/ACMG.pl"
getTrioVar_path: "/data/wangty/WES_pipeline_V2.2/lib/getTrioVar.pl"
getTrio_path: "/data/wangty/WES_pipeline_V2.2/lib/getTrio.pl"
get_result_path: "/data/wangty/WES_pipeline_V2.2/lib/get_result.pl"

# Seem unnecessary but not sure
progress_PATH: "/data/wangty/WES_pipeline_V2.2/lib/process.pl"
getVar2_script_PATH: "/data/wangty/WES_pipeline_V2.2/lib/getVar2.pl"
